In [2]:
import numpy as np
import pandas as pd
import scipy
import statsmodels.api as sm
import seaborn as sns
import sklearn
import matplotlib.pyplot as plt
sns.set()

from sklearn.linear_model import LinearRegression

In [3]:
data = pd.read_csv("C:/Users/Vartotojas/Desktop/Machine learning/Linear regression/1.01. Simple linear regression.csv")
data.head()

SAT   GPA
0  1714  2.40
1  1664  2.52
2  1760  2.54
3  1685  2.74
4  1693  2.83

In [4]:
# independant variable it is called feature x
x = data["SAT"]

# dependant variable it is called target y
y = data["GPA"]

In [29]:
x.shape


(84,)

In [30]:
y.shape

(84,)

In [31]:
# reshape x.shape to x_matrix
x_matrix = x.values.reshape(-1, 1)
x_matrix.shape

(84, 1)

In [32]:
#Regression itself
reg = LinearRegression()

In [33]:
# in fit functions first input x_matrix, then target y
reg.fit(x_matrix, y)

LinearRegression()

In [34]:
# R-squared


In [35]:
reg.score(x_matrix, y)

0.40600391479679765

In [36]:
# Coefficients

In [37]:
reg.coef_

array([0.00165569])

In [38]:
reg.intercept_

0.2750402996602803

In [39]:
#Making predictions

In [39]:
#Making predictions

In [45]:
new_data = pd.DataFrame(data=[1740,1760], columns =["SAT"])
new_data

SAT
0  1740
1  1760

In [46]:
reg.predict(new_data)

C:\Users\Vartotojas\anaconda3\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(


array([3.15593751, 3.18905127])

In [47]:
new_data["Predicted GPA"]=reg.predict(new_data)
new_data

C:\Users\Vartotojas\anaconda3\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(


SAT  Predicted GPA
0  1740       3.155938
1  1760       3.189051

In [49]:
data = pd.read_csv("C:/Users/Vartotojas/Desktop/Machine learning/Linear regression/1.02. Multiple linear regression.csv")

In [50]:
data.head()

SAT  Rand 1,2,3   GPA
0  1714           1  2.40
1  1664           3  2.52
2  1760           3  2.54
3  1685           3  2.74
4  1693           2  2.83

In [51]:
data.describe()

SAT  Rand 1,2,3        GPA
count    84.000000   84.000000  84.000000
mean   1845.273810    2.059524   3.330238
std     104.530661    0.855192   0.271617
min    1634.000000    1.000000   2.400000
25%    1772.000000    1.000000   3.190000
50%    1846.000000    2.000000   3.380000
75%    1934.000000    3.000000   3.502500
max    2050.000000    3.000000   3.810000

In [52]:
#create multiple regression

In [53]:
x = data[["SAT", "Rand 1,2,3"]]
y =data["GPA"]

In [55]:
reg = LinearRegression()
reg.fit(x,y)

LinearRegression()

In [56]:
reg.coef_

array([ 0.00165354, -0.00826982])

In [57]:
reg.intercept_

0.29603261264909486

In [58]:
#calculating R-squared

In [59]:
reg.score(x, y)

0.40668119528142843

In [60]:
# formula for adjusted R^2

In [63]:
r2 = reg.score(x, y)

n = x.shape[0]

p= x.shape[1]

#according to formula:
adjusted_r2 = 1-(1-r2)*(n-1)/(n-p-1)

adjusted_r2

0.39203134825134023

In [64]:
# Feature selection

from sklearn.feature_selection import f_regression

In [65]:
# first array is F-statistics second is P-values
f_regression(x, y)

(array([56.04804786,  0.17558437]), array([7.19951844e-11, 6.76291372e-01]))

In [68]:
# first value 0 is important variable, second value 0.676 is useless
p_values = f_regression(x, y)[1]
p_values.round(3)

array([0.   , 0.676])

In [69]:
#Creating summary table

In [70]:
reg_summary = pd.DataFrame(data=x.columns.values, columns = ["Features"] )
c

Features
0         SAT
1  Rand 1,2,3

In [71]:
reg_summary["Coeficients"]=reg.coef_
reg_summary["P-values"] = p_values.round(3)

In [73]:
reg_summary

Features  Coeficients  P-values
0         SAT     0.001654     0.000
1  Rand 1,2,3    -0.008270     0.676

### STANDARTIZATION

In [75]:
from sklearn.preprocessing import StandardScaler 

In [76]:
scaler = StandardScaler() 

In [77]:
scaler.fit(x)

StandardScaler()

In [79]:
x_scaled = scaler.transform(x)
x_scaled

array([[-1.26338288, -1.24637147],
       [-1.74458431,  1.10632974],
       [-0.82067757,  1.10632974],
       [-1.54247971,  1.10632974],
       [-1.46548748, -0.07002087],
       [-1.68684014, -1.24637147],
       [-0.78218146, -0.07002087],
       [-0.78218146, -1.24637147],
       [-0.51270866, -0.07002087],
       [ 0.04548499,  1.10632974],
       [-1.06127829,  1.10632974],
       [-0.67631715, -0.07002087],
       [-1.06127829, -1.24637147],
       [-1.28263094,  1.10632974],
       [-0.6955652 , -0.07002087],
       [ 0.25721362, -0.07002087],
       [-0.86879772,  1.10632974],
       [-1.64834403, -0.07002087],
       [-0.03150724,  1.10632974],
       [-0.57045283,  1.10632974],
       [-0.81105355,  1.10632974],
       [-1.18639066,  1.10632974],
       [-1.75420834,  1.10632974],
       [-1.52323165, -1.24637147],
       [ 1.23886453, -1.24637147],
       [-0.18549169, -1.24637147],
       [-0.5608288 , -1.24637147],
       [-0.23361183,  1.10632974],
       [ 1.68156984,

In [83]:
#REgression with scaled features

reg = LinearRegression()

reg.fit(x_scaled, y)

LinearRegression()

In [84]:
reg.coef_

array([ 0.17181389, -0.00703007])

In [85]:
reg.intercept_

3.330238095238095

In [90]:
reg_summary = pd.DataFrame([["Bias"], ["SAT"], ["Rand 1,2,3"]], columns = ["Features"])

reg_summary["Weights"]= reg.intercept_, reg.coef_[0], reg.coef_[1]

In [91]:
reg_summary

Features   Weights
0        Bias  3.330238
1         SAT  0.171814
2  Rand 1,2,3 -0.007030

### MAking predictions with standartized coefficients


In [95]:
new_data = pd.DataFrame(data = [[1700, 2], [1800, 1]],columns=["SAT", "Rand 1,2,3"])
new_data 

SAT  Rand 1,2,3
0  1700           2
1  1800           1

In [96]:
reg.predict(new_data)

C:\Users\Vartotojas\anaconda3\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(


array([295.39979563, 312.58821497])

In [97]:
new_data_scaled = scaler.transform(new_data)

In [98]:
reg.predict(new_data_scaled)

array([3.09051403, 3.26413803])

In [99]:
# what if we remove Random 1,2,3 variable?

In [104]:
reg_simple = LinearRegression()
x_simple_matrix = x_scaled[:, 0].reshape(-1, 1)
reg_simple.fit(x_simple_matrix, y)

LinearRegression()

In [107]:
reg_simple.predict(new_data_scaled[:,0].reshape(-1,1))

array([3.08970998, 3.25527879])

In [108]:
from sklearn.model_selection import train_test_split

In [109]:
a = np.arange (1 , 101)

In [110]:
b = np.arange(501, 601)

In [111]:
train_test_split(a)

[array([68, 28, 76, 17, 67, 54, 21, 52, 34, 64, 72, 55, 71, 22, 36, 16,  5,
        29, 23, 98,  3, 70, 78, 30, 73, 10, 33, 18, 83, 42, 93, 24, 92, 31,
        96, 26, 40, 97, 14,  2, 66, 51, 59, 62, 63, 27, 69, 46, 38,  6, 60,
        32, 79, 20, 44, 13, 15, 49, 75,  4, 99,  1, 37, 45, 56, 35, 87, 95,
        89, 39, 86, 85,  7, 82, 91]),
 array([  8,  80,  74,  77,  57,  47,  11,  25,  53,  61,  65,  43,  41,
         48,  81,  50,  84,  88,  94,  19,  90, 100,  12,  58,   9])]

In [148]:
a_train, a_test, b_train, b_test = train_test_split(a, b, test_size=0.2, random_state=365)

In [149]:
a_train.shape, a_test.shape

((80,), (20,))

In [150]:
a_train

array([ 25,  32,  99,  73,  91,  66,   3,  59,  94,   1,   8,  15,  90,
        54,  31,  20,  77,  82,  30,  35,  95,  42,  38,   7,  11,  50,
        21,  48,   2,  17,  10,  58,  68,  43,  41,  16,  88,  72,  79,
       100,  80,  39,  24,  86,  22,  23,  62,  76,  18,  47,  55,  26,
        60,  19,  71,  64,  51,  63,  65,  28,  12,  78,  13,  44,  75,
        87,  40,   4,  29,  49,  37,  57,  27,  74,   6,  45,  92,  34,
        53,  83])

In [151]:
a_test

array([ 9, 69, 81, 56, 33, 93, 84, 61, 46, 89, 85, 67, 97,  5, 70, 36, 98,
       96, 14, 52])

In [152]:
b_train.shape, b_test.shape

((80,), (20,))

In [153]:
b_train

array([525, 532, 599, 573, 591, 566, 503, 559, 594, 501, 508, 515, 590,
       554, 531, 520, 577, 582, 530, 535, 595, 542, 538, 507, 511, 550,
       521, 548, 502, 517, 510, 558, 568, 543, 541, 516, 588, 572, 579,
       600, 580, 539, 524, 586, 522, 523, 562, 576, 518, 547, 555, 526,
       560, 519, 571, 564, 551, 563, 565, 528, 512, 578, 513, 544, 575,
       587, 540, 504, 529, 549, 537, 557, 527, 574, 506, 545, 592, 534,
       553, 583])

In [154]:
b_test

array([509, 569, 581, 556, 533, 593, 584, 561, 546, 589, 585, 567, 597,
       505, 570, 536, 598, 596, 514, 552])